

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - .:/app
    command: uvicorn src.infrastructure.api.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  db-data:

networks:
  app-network:
    driver: bridge